# infrastructure/docker/docker-compose.yml
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sourceban
    ports: ["5432:5432"]
  adminer:
    image: adminer
    ports: ["8080:8080"]
    depends_on: [postgres]